[package]
name = "jimbot-desktop"
version = "0.1.0"
edition = "2021"


[dependencies]
jimbot = { path = "../jimbot" }
ringbuf = "0.2.7"
cpal = { version = "0.13.5", features = ["wasm-bindgen"] }
bevy = "0.6.1"
bevy_egui = "0.12.1"
pretty-hex = "0.2.1"
