#[derive(Debug)]
pub enum CartridgeType {
    RomOnly,
    RomMbc1,
    RomMbc1Ram,
    RomMbc1RamBattery,
    RomMbc2,
    RomMbc2Battery,
    RomRam,
    RomRamBattery,
    RomMmm01,
    RomMmm01Sram,
    RomMmm01SramBattery,
    RomMbc3TimerBattery,
    RomMbc3TimerRamBattery,
    RomMbc3,
    RomMbc3Ram,
    RomMbc3RamBattery,
    RomMbc5,
    RomMbc5Ram,
    RomMbc5RamBattery,
    RomMbc5Rumble,
    RomMbc5RumbleSram,
    RomMbc5RumbleSramBattery,
    PocketCamera,
    BandaiTama5,
    HudsonHuC3,
    HudsonHuC1,
    Unknown,
}

impl From<u8> for CartridgeType {
    fn from(byte: u8) -> Self {
        match byte {
            0x00 => CartridgeType::RomOnly,
            0x01 => CartridgeType::RomMbc1,
            0x02 => CartridgeType::RomMbc1Ram,
            0x03 => CartridgeType::RomMbc1RamBattery,
            0x05 => CartridgeType::RomMbc2,
            0x06 => CartridgeType::RomMbc2Battery,
            0x08 => CartridgeType::RomRam,
            0x09 => CartridgeType::RomRamBattery,
            0x0B => CartridgeType::RomMmm01,
            0x0C => CartridgeType::RomMmm01Sram,
            0x0D => CartridgeType::RomMmm01SramBattery,
            0x0F => CartridgeType::RomMbc3TimerBattery,
            0x10 => CartridgeType::RomMbc3TimerRamBattery,
            0x11 => CartridgeType::RomMbc3,
            0x12 => CartridgeType::RomMbc3Ram,
            0x13 => CartridgeType::RomMbc3RamBattery,
            0x19 => CartridgeType::RomMbc5,
            0x1A => CartridgeType::RomMbc5Ram,
            0x1B => CartridgeType::RomMbc5RamBattery,
            0x1C => CartridgeType::RomMbc5Rumble,
            0x1D => CartridgeType::RomMbc5RumbleSram,
            0x1E => CartridgeType::RomMbc5RumbleSramBattery,
            0x1F => CartridgeType::PocketCamera,
            0xFD => CartridgeType::BandaiTama5,
            0xFE => CartridgeType::HudsonHuC3,
            0xFF => CartridgeType::HudsonHuC1,
            _ => panic!("Unknown cartridge type: {:#02x}", byte)
        }
    }
}
